name: User CI

on:
  push:
    paths:
    - 'user-server/**'
    tags:
    - 'u_*'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run MySQL container
      working-directory: ./user-server
      run: |
        docker build -t custom-mysql .
        docker run -d --name test-mysql -p 3306:3306 custom-mysql
        docker ps    

    - name: Make application.yaml
      run: |
        cd user-server
        touch ./src/main/resources/application.yaml
        echo "${{ secrets.AWS_USER_PROPERTIES }}" > ./src/main/resources/application.yaml

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./user-server/gradlew

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_CI_ROLE }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Confirm Image Tag
      run: echo $IMAGE_TAG

    - name: Build and Push Docker image with Jib
      run: |
        cd user-server
        ./gradlew jib --image=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_USER_SERVER_REPO }}:${{ env.IMAGE_TAG }}